export const apiUrl = {
    Auth: process.env.REACT_APP_API_AUTH_URL,
    Cupos: process.env.REACT_APP_API_CUPOS_URL,
    Parametros: process.env.REACT_APP_API_PARAMETROS_URL,
    Permissions: process.env.REACT_APP_API_PERMISSIONS_URL,
    RecaptchaURL: process.env.REACT_APP_RECAPTCHA_URL,
    Representantes: process.env.REACT_APP_API_REPRESENTANTES_URL,
    RepresentantePatentes: process.env.REACT_APP_API_REPRESENTANTE_PATENTES_URL,
    Roles: process.env.REACT_APP_API_ROLES_URL,
    Talonarios: process.env.REACT_APP_API_TALONARIOS_URL,
    Terminales: process.env.REACT_APP_API_TERMINALES_URL,
    Translation: process.env.REACT_APP_API_TRANSLATION_URL,
    Users: process.env.REACT_APP_API_USERS_URL,
    UserRoles: process.env.REACT_APP_API_USER_ROLES_URL,
    UserTypes: process.env.REACT_APP_API_USER_TYPES_URL,
    Contenidos: process.env.REACT_APP_API_CONTENIDO_URL,
    TalonarioTickets: process.env.REACT_APP_API_TALONARIO_TICKETS_URL,
}